var textoLorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel sodales odio. Curabitur dignissim, ipsum quis semper feugiat, dui lectus commodo ligula, at fringilla quam tortor sed libero. Curabitur at dignissim est. Mauris hendrerit lorem at augue pretium, sed efficitur justo rutrum. Aenean hendrerit et lacus non pharetra. Pellentesque blandit consectetur consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eu ultricies massa. Sed auctor lacus fermentum vehicula varius. Quisque eleifend est in tellus laoreet, id pulvinar lectus ullamcorper. Suspendisse mattis dignissim tempus. Integer eu cursus tellus. Etiam porta dapibus enim at consequat. Proin ultricies nulla ut nunc rhoncus, ac ullamcorper sapien facilisis. Nam aliquet semper congue. Quisque a ex dapibus magna congue egestas.

Pellentesque neque purus, facilisis in erat eget, suscipit varius dui. Proin consequat eros id mattis placerat. Aliquam erat volutpat. Sed et tempor massa. Proin quis ultrices lectus. Maecenas scelerisque accumsan aliquet. Donec eleifend dolor ut enim tempus, sit amet efficitur quam cursus. Proin ex enim, lacinia in arcu non, ornare molestie ligula. Suspendisse potenti. Donec bibendum fermentum tellus sed aliquet. Donec nisl nunc, aliquam ut interdum ac, semper in nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc volutpat a lacus non euismod. Donec dictum, tellus id porta efficitur, turpis ligula iaculis dolor, eu bibendum tellus nisi quis orci.

Suspendisse neque lacus, ornare nec fringilla sed, suscipit et eros. Integer convallis sodales massa, eget sollicitudin quam. Nulla facilisi. Nunc molestie, tellus ut malesuada dapibus, risus sapien pulvinar neque, non feugiat nisi leo sed ipsum. Sed eget facilisis orci, pellentesque dignissim est. Cras sit amet dolor nec lorem semper aliquam. Nullam non nunc tortor. Vivamus consequat lectus ex, ut pretium sem fringilla id. Aliquam at urna sollicitudin, mattis leo et, lacinia lectus. Maecenas nec aliquam augue, vitae interdum elit. Mauris leo nisl, aliquam eget ligula vel, lobortis porta lorem. In faucibus quis lectus a pulvinar. Donec vel nulla varius, fermentum mauris a, aliquet nunc. Sed ultricies placerat justo ut dignissim. Integer consequat purus non sollicitudin lobortis.

Proin vitae nisl mi. Proin a justo commodo, faucibus neque eget, tempor massa. Nam a faucibus dui, eget fermentum nisl. Ut ut tempus justo, vitae ornare nisl. Mauris venenatis consequat est. Nulla ut suscipit lectus. Nunc et arcu id ante euismod vestibulum. Quisque nulla odio, porttitor non tempor viverra, bibendum ac felis. Sed tempor mauris imperdiet orci tristique, in finibus elit ultrices. Sed pharetra libero a tortor lobortis interdum sed et urna. Aliquam at dictum mi. Donec tempor quam dui. Phasellus diam leo, faucibus a ultrices at, fermentum sit amet ligula. Aenean sollicitudin, mauris vel facilisis iaculis, massa dolor consequat mauris, at imperdiet quam metus et nibh. Nunc massa mauris, finibus sit amet neque vel, maximus euismod ex. Etiam non nisi mi.

Phasellus quis sapien leo. Proin tincidunt id nulla ac condimentum. Nunc dictum nibh vel tempor pellentesque. Cras ultricies urna ipsum, ut iaculis ex volutpat at. Sed orci tortor, consequat vel tellus quis, malesuada suscipit dui. Pellentesque lectus nulla, rutrum a ultricies eget, laoreet sed diam. Pellentesque diam est, feugiat sit amet ornare in, vulputate non augue. Donec eu erat rhoncus erat volutpat iaculis. Vestibulum rutrum metus purus, vitae aliquam diam facilisis non. Praesent volutpat elit ac ex ultricies, sit amet laoreet elit posuere.

Donec ac feugiat velit. Aliquam eget finibus nisl. Sed a massa ante. Maecenas tempus justo sed metus fermentum semper. In sodales euismod ornare. Aliquam eleifend volutpat maximus. Cras egestas velit tempor velit suscipit, nec rhoncus lacus ultrices. Praesent aliquet, risus ac auctor feugiat, purus ante pulvinar dui, ac volutpat erat enim ut purus.

Phasellus justo dui, convallis quis sagittis nec, feugiat eget lectus. Curabitur at urna bibendum, porta lacus eu, bibendum magna. Sed massa justo, iaculis id tristique eu, porttitor at dolor. Proin eget lobortis nunc. Curabitur non magna eros. Vestibulum urna dui, luctus a velit vitae, malesuada scelerisque quam. Sed ac porttitor lacus. Nunc posuere libero nec leo tristique, quis luctus elit semper. Donec eleifend elit consectetur metus lobortis finibus. Proin tincidunt dapibus aliquet. Morbi vitae feugiat erat. Nulla mattis felis id ullamcorper congue. Phasellus dapibus sapien felis, vitae sagittis libero varius nec. Ut nulla sapien, bibendum non neque aliquam, facilisis tincidunt eros. Pellentesque finibus lacus id leo porttitor laoreet ut sit amet libero.

Sed arcu magna, dictum a odio quis, porta aliquam ex. Suspendisse potenti. Suspendisse ac velit mattis, tincidunt risus sed, posuere magna. Vivamus ultrices facilisis leo id elementum. Etiam condimentum vel lorem sit amet scelerisque. Cras aliquam, leo eget hendrerit aliquam, nisi eros dictum purus, ut accumsan augue mi a augue. Quisque faucibus elementum est a aliquam. Sed erat ligula, porttitor a faucibus eget, aliquet non tortor. Cras ullamcorper suscipit egestas. Donec vel turpis ac elit vestibulum fringilla. Praesent feugiat massa vitae elit lacinia, volutpat lacinia tortor luctus. Vestibulum tempor, massa a mollis pulvinar, diam purus cursus elit, eu commodo nunc est non lacus. Curabitur nulla risus, rhoncus lacinia dignissim ac, consectetur id erat.
da nunc metus quis velit. Sed elementum purus id commodo eleifend. Sed tincidunt sapien ac libero bibendum elementum. Proin et magna sem. Cras dapibus metus ac leo placerat cursus. Vivamus pellentesque velit sed risus laoreet laoreet. Donec quis diam nec purus fringilla consequat facilisis nec nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque quis bibendum mi, sed semper ligula. Sed at est tellus.

Donec id laoreet magna, vel aliquam lectus. Quisque felis ante, luctus eget urna in, ultrices tincidunt tellus. Sed aliquam nec libero vitae imperdiet. Mauris iaculis nibh in enim gravida varius. Nam venenatis tincidunt risus, ac congue massa dapibus et. Quisque eget convallis nibh. Fusce orci sapien, tincidunt vel efficitur ac, tincidunt eget mauris. Pellentesque rutrum risus sed dolor pulvinar ornare. Donec ac mollis neque. Nullam non bibendum lorem.`;
